package com.oldmen.superapp;

public class Data {

    public static final String DISCOVERY_STRING = "[{\"id\":\"a1\",\"type\":\"TEXT\",\"url\":\"\",\"title\":\"Pratilipi Hackathon\",\"category\":\"Update\",\"description\":\"Know whats going on in the pratilipi hackathon\", \"members\":\"40\", \"logo\":\"https://github.com/androdev700/SuperApp/raw/master/logos/pratilipi.png\"}," +
            "{\"id\":\"a29\",\"type\":\"IMAGE\",\"url\":\"\",\"title\":\"YourQuote\",\"category\":\"Entertainment\",\"description\":\"YourQuote is a writing app for writers and performers, compose shayari, poems, thoughts, opinions and status on beautiful images and wallpapers\",\"rating\":4, \"members\":\"8342\", \"logo\":\"https://github.com/androdev700/SuperApp/raw/master/logos/yourquote.png\"}," +
            "{\"id\":\"a2\",\"type\":\"WEB\",\"url\":\"https://www.bbc.com/\",\"title\":\"BBC India.\",\"category\":\"News, Media, Entertainment\",\"description\":\"Breaking news, sport, TV, radio and a whole lot more. The BBC informs, educates and entertains - wherever you are, whatever your age.\", \"members\":\"8,26,393\", \"logo\":\"https://github.com/androdev700/SuperApp/raw/master/logos/bbc.jpg\" }, " +
            "{\"id\":\"a17\",\"type\":\"WEB\",\"url\":\"https://www.spotify.com/in/\",\"title\":\"Spotify\",\"category\":\"Music, Records, Albums\",\"description\":\"Spotify is a digital music service that gives you access to millions of songs.\", \"members\":\"3,34,36,936\", \"logo\":\"https://github.com/androdev700/SuperApp/raw/master/logos/spotify.png\" }, " +
            " {\"id\":\"a3\",\"type\":\"WEB\",\"url\":\"https://economictimes.indiatimes.com/\",\"title\":\"Economic times.\",\"category\":\"News, Media, Entertainment\",\"description\":\"Business News- Read Latest Financial news, Stock/Share Market News, Economy News, Business News on The Economic Times.  Find IPO Analysis, Mutual Funds Trends & Analysis, Gold Rate, Real Estate & more. \", \"members\":\"1,89,364\", \"logo\":\"https://github.com/androdev700/SuperApp/raw/master/logos/economics-time.png\" } ," +
            "{\"id\":\"a20\",\"type\":\"WEB\",\"url\":\"https://goldsgym.in/\",\"title\":\"Golds Gym\",\"category\":\"Fitness, Body building, Cross-fit training\",\"description\":\"Gold's Gym is acknowledged for its unrivaled success in providing the finest equipment and fitness knowledge to help its members achieve their goals.\", \"members\":\"64,36,936\", \"logo\":\"https://github.com/androdev700/SuperApp/raw/master/logos/goldgym.png\" }," +
            "{\"id\":\"a5\",\"type\":\"WEB\",\"url\":\"https://www.trivago.in/\",\"title\":\"Trivago\",\"category\":\"Hotels, Holidays, Bookings\",\"description\":\"Compare hotel prices and get great deals. Save time and money on your accommodation search with millions of reviews and photos on trivago.in\", \"members\":\"27,23,784\", \"logo\":\"https://github.com/androdev700/SuperApp/raw/master/logos/trivago.png\" }," +
            "{\"id\":\"a7\",\"type\":\"WEB\",\"url\":\"https://unacademy.com/\",\"title\":\"Unacademy\",\"category\":\"Online courses, Tutorials\",\"description\":\"Prepare for examinations and take any number of courses from various topics on Unacademy - an education revolution\", \"members\":\"8,23,678\", \"logo\":\"https://github.com/androdev700/SuperApp/raw/master/logos/unacademy.jpg\" }," +
            "{\"id\":\"a10\",\"type\":\"WEB\",\"url\":\"https://www.zomato.com\",\"title\":\"Zomato\",\"category\":\"Find Restaurants, Order Food Online\",\"description\":\"Bengaluru Restaurants - Menus, Photos, Ratings and Reviews for over 19000 Restaurants in Bengaluru. Find the Best Restaurants in Bengaluru on Zomato - Bengaluru Restaurants\", \"members\":\"7,34,984\", \"logo\":\"https://github.com/androdev700/SuperApp/raw/master/logos/zomato.png\"},"+
            "{\"id\":\"a8\",\"type\":\"WEB\",\"url\":\"https://www.coursera.org/\",\"title\":\"Coursera\",\"category\":\"Online courses, Tutorials\",\"description\":\"Choose your #CourseToSuccess! Learn online and earn valuable credentials from top universities like Yale, Michigan, Stanford, and leading companies like Google and IBM.\", \"members\":\"2,948,758\", \"logo\":\"https://github.com/androdev700/SuperApp/raw/master/logos/coursera.png\"},"+
            "{\"id\":\"a19\",\"type\":\"WEB\",\"url\":\"https://www.flipkart.com/\",\"title\":\"Flipkart\",\"category\":\"E-Commerce, Online Shopping\",\"description\":\"Online Shopping Site for Mobiles, Electronics, Furniture, Grocery, Lifestyle, Books & More. Best Offers!\", \"members\":\"1,34,36,936\", \"logo\":\"https://github.com/androdev700/SuperApp/raw/master/logos/flipkart.png\"},"+
            "{\"id\":\"a11\",\"type\":\"WEB\",\"url\":\"https://www.swiggy.com\",\"title\":\"Swiggy\",\"category\":\"Order Food Online, Food Delivery\",\"description\":\"Order food online from restaurants and get it delivered. Serving in Bangalore, Hyderabad, Delhi, Gurgaon, Nagpur, Jaipur, Coimbatore, Chandigarh, Ahemdabad, Visakhapatnam, Lucknow, Noida, Mumbai, Pune, Indore, Kochi, Kolkata and Chennai. Order Pizzas, Burgers, Biryanis, Desserts or order from Subway, Pizza Hut, Dominos, KFC, McDonalds.\", \"members\":\"8,73,489\", \"logo\":\"https://github.com/androdev700/SuperApp/raw/master/logos/swiggy.png\"},"+
            "{\"id\":\"a15\",\"type\":\"WEB\",\"url\":\"https://www.voot.com/\",\"title\":\"Voot\",\"category\":\"Movies, Seasons, Documentaries\",\"description\":\"Voot - Watch free online streaming of your favourite TV Shows, Movies, Kids Shows - Hindi, Tamil, Bengali, Kannada and more with Colors, MTV, NICK and many of your favourite channels in HD quality on, India’s leading online streaming platform.\", \"members\":\"62,36,936\", \"logo\":\"https://github.com/androdev700/SuperApp/raw/master/logos/voot.jpg\"},"+
            "{\"id\":\"a12\",\"type\":\"WEB\",\"url\":\"http://www.rovio.com/\",\"title\":\"Angry birds\",\"category\":\"Mobile Game, Bird Game\",\"description\":\"The home of Rovio - maker of Angry Birds, Bad Piggies, Nibblers, BattleBay and many more!\", \"members\":\"8,73,489\", \"logo\":\"https://github.com/androdev700/SuperApp/raw/master/logos/angry_birds.jpg\"},"+
            "{\"id\":\"a4\",\"type\":\"WEB\",\"url\":\"https://www.makemytrip.com/\",\"title\":\"MakeMyTrip\",\"category\":\"Travel, Holidays\",\"description\":\"Find best deals at MakeMyTrip for ✅ Flight Tickets, Hotels, Holiday Packages, Bus and Train / Railway Reservations for India & International travel. Book cheap air tickets online for Domestic & International airlines, customized holiday packages and special deals on Hotel Bookings.\", \"members\":\"89,34,567\", \"logo\":\"https://github.com/androdev700/SuperApp/raw/master/logos/makemytrip.jpg\"},"+
            "{\"id\":\"a9\",\"type\":\"WEB\",\"url\":\"https://www.khanacademy.org/\",\"title\":\"Khan Academy\",\"category\":\"Online courses, Tutorials\",\"description\":\"Learn for free about math, art, computer programming, economics, physics, chemistry, biology, medicine, finance, history, and more. Khan Academy is a nonprofit with the mission of providing a free, world-class education for anyone, anywhere.\", \"members\":\"7,948,758\", \"logo\":\"https://github.com/androdev700/SuperApp/raw/master/logos/khan.jpg\"},"+
            "{\"id\":\"a13\",\"type\":\"WEB\",\"url\":\"https://www.netflix.com\",\"title\":\"Netflix\",\"category\":\"Movies, Seasons, Documentaries\",\"description\":\"Watch Netflix films & TV programmes online or stream right to your smart TV, game console, PC, Mac, mobile, tablet and more.\", \"members\":\"8,92,36,936\", \"logo\":\"https://github.com/androdev700/SuperApp/raw/master/logos/Netflix_icon.png\"},"+
            "{\"id\":\"a14\",\"type\":\"WEB\",\"url\":\"https://www.primevideo.com\",\"title\":\"Primefolder\",\"category\":\"Movies, Seasons, Documentaries\",\"description\":\"Enjoy exclusive Amazon Originals as well as popular movies and TV shows.  Watch anytime, anywhere. Start your free trial.\", \"members\":\"1,02,36,936\", \"logo\":\"https://github.com/androdev700/SuperApp/raw/master/logos/primevideo.png\"},"+
            "{\"id\":\"a16\",\"type\":\"WEB\",\"url\":\"https://www.audible.in\",\"title\":\"Audible\",\"category\":\"Audio books, e-books\",\"description\":\"Great books narrated by great performers. With over 200,000 audiobooks, you are sure to find the perfect listen. Download audiobooks to your iPhone, Android, or other listening devices. Start your free trial today and get a free audiobook. Listen to your books wherever you are with the free Audible app - in a car, on a run or even when ironing! \", \"members\":\"62,36,936\", \"logo\":\"https://github.com/androdev700/SuperApp/raw/master/logos/audible.jpg\"},"+
            "{\"id\":\"a18\",\"type\":\"WEB\",\"url\":\"https://www.amazon.in\",\"title\":\"Amazon\",\"category\":\"E-Commerce, Online Shopping\",\"description\":\"Amazon.in: Online Shopping India - Buy mobiles, laptops, cameras, books, watches, apparel, shoes and e-Gift Cards. Free Shipping & Cash on Delivery Available.\", \"members\":\"7,34,36,936\", \"logo\":\"https://github.com/androdev700/SuperApp/raw/master/logos/amazon.png\"},"+
            "{\"id\":\"a1\",\"type\":\"WEB\",\"url\":\"https://www.ndtv.com\",\"title\":\"NDTV 24X7\",\"category\":\"News, Media, Entertainment\",\"description\":\"NDTV.com provides latest news from India and the world. Get today’s news headlines from Business, Technology, Bollywood, Cricket, videos, photos, live news coverage and exclusive breaking news from India.\", \"members\":\"6,83,856\", \"logo\":\"https://github.com/androdev700/SuperApp/raw/master/logos/ndtv.jpg\"},"+
            "{\"id\":\"a6\",\"type\":\"WEB\",\"url\":\"https://www.uber.com/in/en\",\"title\":\"Uber India\",\"category\":\"Cabs, Car rentals, Intercity Cabs\",\"description\":\"Get a ride in minutes. Or become a driver and earn money on your schedule. Uber is finding you better ways to move, work, and succeed.\", \"members\":\"7,78,345\", \"logo\":\"https://github.com/androdev700/SuperApp/raw/master/logos/uber.jpg\"},"+
            "{\"id\":\"a21\",\"type\":\"WEB\",\"url\":\"https://www.cure.fit\",\"title\":\"Cure fit\",\"category\":\"Fitness, Body building, Cross-fit training\",\"description\":\"Order Food Online at Eat.Fit | Get Trained In Yoga, Zumba & Sports Workouts At Cult.Fit | Learn Meditation, Pranayama & more At Mind.Fit | Be Healthy & Fit With Cure.Fit.\", \"members\":\"1,74,36,936\", \"logo\":\"https://github.com/androdev700/SuperApp/raw/master/logos/cult.png\"}"+
            "]";

    public static final String UPDATE_STRING = "[" +
            "{\"id\":\"a11\",\"message\":\"10 minutes to start. Environment here is electric\",\"time\":\"1150 Hours\"}," +
            "{\"id\":\"a12\",\"message\":\"GO!GO!GO!\",\"time\":\"1200 Hours\"}," +
            "{\"id\":\"a13\",\"message\":\"Teams are settled down in their areas\",\"time\":\"1300 Hours\"}," +
            "{\"id\":\"a14\",\"message\":\"2 hours done, jobless PMs can be seen roaming around\",\"time\":\"1400 Hours\"}," +
            "{\"id\":\"a15\",\"message\":\"SANDWICH TIME..\",\"time\":\"1500 Hours\"}," +
            "{\"id\":\"a16\",\"message\":\"PIZZA IS HERE..Non vegetarians, you better hurry! \",\"time\":\"1600 Hours\"}," +
            "{\"id\":\"a17\",\"message\":\"Sakht Tea time.\",\"time\":\"1800 Hours\"}" +
            "]";

    public static final String SHARE_CHATE_STRING = "[" +
            "{\"id\":\"a20\",\"image\":\"https://github.com/androdev700/SuperApp/raw/master/logos/yourquote1.png\"}," +
            "{\"id\":\"a21\",\"image\":\"https://github.com/androdev700/SuperApp/raw/master/logos/yourquote2.png\"}," +
            "{\"id\":\"a23\",\"image\":\"https://github.com/androdev700/SuperApp/raw/master/logos/yourquote3.png\"}," +
            "{\"id\":\"a24\",\"image\":\"https://github.com/androdev700/SuperApp/raw/master/logos/yourquote4.jpg\"}," +
            "{\"id\":\"a25\",\"image\":\"https://github.com/androdev700/SuperApp/raw/master/logos/yourquote5.png\"}," +
            "{\"id\":\"a26\",\"image\":\"https://github.com/androdev700/SuperApp/raw/master/logos/yourquote6.jpg\"}," +
            "{\"id\":\"a28\",\"image\":\"https://github.com/androdev700/SuperApp/raw/master/logos/yourquote8.png\"}" +
            "]";

    public static final String HOME_SCREEN_DEMO_DATA = "[" +
            "{\"id\":\"b1\",\"image\":\"https://github.com/androdev700/SuperApp/raw/master/logos/neetu.jpg\",\"title\":\"Neetu\",\"description\":\"Yes i am on sick leave, but i am going to a movie\",\"secondaryText\":\"5secs ago\"}," +
            "{\"id\":\"b2\",\"image\":\"https://github.com/androdev700/SuperApp/raw/master/logos/yoga.png\",\"title\": \"Fitness\",\"description\":\"It's time to take a break and meditate for 2 mins. Deep breaths..\",\"secondaryText\":\"1min ago\"}," +
            "{\"id\":\"b3\",\"image\":\"https://github.com/androdev700/SuperApp/raw/master/logos/freshmenu_1.jpg\",\"title\": \"Freshmenu\",\"description\":\"You order is been picked. Clieck to track order\",\"secondaryText\":\"1min ago\"}, " +
            "{\"id\":\"b4\",\"image\":\"https://github.com/androdev700/SuperApp/raw/master/logos/wife.jpg\",\"title\": \"Horror at home\",\"description\":\"Missing you dear...\",\"secondaryText\":\"2mins ago\"}," +
            "{\"id\":\"b5\",\"image\":\"https://github.com/androdev700/SuperApp/raw/master/logos/coursera.png\",\"title\": \"Coursera\",\"description\":\"Writing Asynchronous Programs in JavaScript\",\"secondaryText\":\"3mins ago\"}, " +
            "{\"id\":\"b6\",\"image\":\"https://github.com/androdev700/SuperApp/raw/master/logos/ptlpcofndrs.jpg\",\"title\": \"Cofounders\",\"description\":\"Ranjeet: We are going public on 2022\",\"secondaryText\":\"4mins ago\"}, " +
            "{\"id\":\"b7\",\"image\":\"https://github.com/androdev700/SuperApp/raw/master/logos/giridhar.jpg\",\"title\": \"Giridhar\",\"description\":\"Yo!!! old man...\",\"secondaryText\":\"7mins ago\"}" +
            "]";
}
